version: "3.9"

volumes:
  db_data:
  mlflow_data:
  ftp_data:
  sftp_data:
services:
  db:
    image: postgres:13.5
    environment:
      POSTGRES_USER: "mlops"
      POSTGRES_PASSWORD: "mlops"
      POSTGRES_DB: "mlflow"
    ports:
      - 15432:5432
    volumes:
      - db_data:/var/lib/postgresql/data

  ftp_server:
    image: delfer/alpine-ftp-server
    ports:
      - 10021:21
      - 21:21
      - 21000-21010:21000-21010
    environment:
      USERS: "mlops|mlops|data"
    volumes:
      - ftp_data:/data

  mlflow:
    depends_on:
      - db
      - ftp_server
    build:
      context: .
      dockerfile: Dockerfile.mlflow
    ports:
      - 5000:5000
    command:
      - bash
      - -c
      - mlflow server
        --host 0.0.0.0
        --backend-store-uri="postgresql://mlops:mlops@db:5432/mlflow"
        --default-artifact-root="ftp://mlops:mlops@ftp_server/data"
        --serve-artifacts
        --artifacts-destination="ftp://mlops:mlops@ftp_server"

  model_server:
    depends_on:
      - mlflow
    build:
      context: .
      dockerfile: Dockerfile.serve_model
    ports:
      - 8000:80
    command: bash -c "uvicorn my_model.serving.__main__:app --host 0.0.0.0 --port 80 --workers 2"